apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx0-deployment
  labels:
    app: nginx0-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx
        image: 834406757853.dkr.ecr.ap-south-1.amazonaws.com/test:$(cat version/number)
        #image: 834406757853.dkr.ecr.ap-south-1.amazonaws.com/test:0.0.36
        #imagePullPolicy: Always
        #image: nginx:latest
        ports:
        - containerPort: 80
